### PR TITLE
Use wrk2 and add non-keepalive benchmark & 10000~60000 connections benchmark

### PR DESCRIPTION
**Pull request by xfeep**
Use wrk2 and add non-keepalive benchmark & 10000~60000 connections benchmark. More details can be found at #21.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Zhang, 

Thank you very much for your efforts! I'm sorry for taking so long to look at your PR properly.

There are many changes here and they are a bit difficult to make sense of, so I have taken some time to try and clean up your pull request on the [xfeep-merge branch](https://github.com/ptaoussanis/clojure-web-server-benchmarks/commits/xfeep-merge).

I've broken the commits down as logically as I could, and made some style (mostly formatting) changes so that I could understand the code better. I hope that I have not made any errors.

The upgrade to wrk2 is a good one, and I'm happy that you have made the new test config (e.g. connection count, keep alive) something configurable.

I would like to ask for one change. Instead of adding many new scripts `run-benchmarks.sh`, `run-benchmarks-nonkeepalive.sh`, `run-benchmarks-largeNumOfConns.sh`, etc.  - I think it would be better if we kept just _one_ of each script and instead added optional script arguments to control these extra options.

So I would like that we keep only one set of scripts (bench.sh, run-benchmarks.sh, run-servers.sh, strip-results.sh, tune-os.sh) - and keep any optional changes as optional arguments to these scripts.

Does that make sense?

Could I ask you to **add** one new commit **to the current [xfeep-merge branch](https://github.com/ptaoussanis/clojure-web-server-benchmarks/commits/xfeep-merge)** which makes this change? I.e. please reset your local repo to commit 3ca5c4416fcb7da778c931009deaf8f94601a128 so that we're working from the same place.

Then I will continue to look through the rest of the PR and organise your results into a new README.

Is that okay? Please feel free to ask if you have any questions. Thanks again! :-)

**Comment by xfeep** [comment]
@ptaoussanis Thanks for your advice which I totally agree with. :-)
The next few days if I have time I will do it .

**Comment by ptaoussanis** [comment]
@xfeep Great, thank you very much!

I would maybe suggest setting up a single argument to `run-servers.sh` which specifies a named test profile? We can then define all the named profiles in the same file with different options: connection counts, keep alive settings, and anything else that may come up later.

So then people can call `run-servers.sh defaults` or `run-servers.sh xfeep-60k-nokeepalive`, etc. and the specified tests will run.

By keeping everything in one file, it might be easier to share code (e.g. shared logging / printouts) and easier to understand/maintain when we have many contributors like we do here. If someone has a new test type to add, they know exactly where to go and how to define it.

Named profiles can also let us start grouping/organising our results better: `/results/defaults`, `results/xfeep-60k-nokeepalive`, etc.

Cheers :-)

**Comment by xfeep** [comment]
@ptaoussanis I plant to define three test profiles. e.g When we run scripts/run-benchmarks.sh

it will display usage infomation just like 
```
$ scripts/run-benchmarks.sh 
Usage: scripts/run-benchmarks.sh profile
profiles:
  1k-keepalive         Start  benchmark with keepalive connections ranging  from 32 ~ 1024
  1k-nonkeepalive      Start  benchmark with non-keepalive connections ranging  from 32 ~ 1024
  60k-keepalive        Start  benchmark with keepalive connections ranging  from 10000 ~ 60000
  60k-nonkeepalive     Start  benchmark with non-keepalive connections ranging  from 10000 ~ 60000
```

The raw result file name will be  

```
results/20150129-03-55-${profile_name}
```

The stripped result file name will be

```
results/20150129-03-55-${profile_name}.stripped
```

The text table and charts file names will be

```
results/20150129-03-55-${profile_name}-table.txt
results/20150129-03-55-${profile_name}-qps.png
.....
```

Any more suggestions? :-)

**Comment by ptaoussanis** [comment]
That sounds great.

> Any more suggestions? :-)

Maybe use a `results/${profile_name}/20150129-03-55` path instead of `results/20150129-03-55-${profile_name}`?

That way people can easily look up results based on the test profile they're interested in. We can organise the results in the README in the same way. What do you think?

**Comment by xfeep** [comment]
@ptaoussanis
>Maybe use a results/${profile_name}/20150129-03-55 path instead of results/20150129-03-55-${profile_name}?

 No problem.

@shenfeng Hi, ShenFeng. We have trouble doing non-keepalive benchmark with http-kit (listens at port 8087). When use `wrk -t 1 -c 100 -d 20s -H 'Connection: Close' http://127.0.0.1:8087/` to test with http-kit. The result is strange.

```
Running 20s test @ http://127.0.0.1:8087/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us  100.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  136 requests in 20.01s, 170.53KB read
  Socket errors: connect 0, read 36, write 0, timeout 900
Requests/sec:      6.80
Transfer/sec:      8.52KB
```

Maybe was it caused by that http-kit didn't reply with header 'Connection: Close' to wrk ?  And then wrk did not close the socket but http-kit thought it was closed? 

Would you please give any suggestions?

BTW the wrk is the latest version and wrk2 is with [this patch](https://github.com/wg/wrk/issues/118#issuecomment-72155351) which was merged into the latest wrk.

**Comment by ptaoussanis** [comment]
@xfeep I believe @shenfeng has been quite busy recently. If you don't hear back from him, please feel free to submit the PR without http-kit results for the no-keep-alive test for now.

**Comment by xfeep** [comment]
@ptaoussanis a new PR #25 was created.

**Pull request closed without merging**
